// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1QniUDgP2Bw1036LZE_7AX-pZFLFpKI',
    appId: '1:277847481010:web:73229652190e842b0847ab',
    messagingSenderId: '277847481010',
    projectId: 'smart-task-manager-2026',
    authDomain: 'smart-task-manager-2026.firebaseapp.com',
    storageBucket: 'smart-task-manager-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLNarfIqfwRDflNceBiiFKNf5EtaP2Yg',
    appId: '1:277847481010:android:97e3d92c17746c150847ab',
    messagingSenderId: '277847481010',
    projectId: 'smart-task-manager-2026',
    storageBucket: 'smart-task-manager-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJR7J1IpPE9jbFRbWGrKm7RUo5OyZ3TOw',
    appId: '1:277847481010:ios:ebd7bf9dc9f829440847ab',
    messagingSenderId: '277847481010',
    projectId: 'smart-task-manager-2026',
    storageBucket: 'smart-task-manager-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskManger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJR7J1IpPE9jbFRbWGrKm7RUo5OyZ3TOw',
    appId: '1:277847481010:ios:ebd7bf9dc9f829440847ab',
    messagingSenderId: '277847481010',
    projectId: 'smart-task-manager-2026',
    storageBucket: 'smart-task-manager-2026.firebasestorage.app',
    iosBundleId: 'com.example.smartTaskManger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf1QniUDgP2Bw1036LZE_7AX-pZFLFpKI',
    appId: '1:277847481010:web:5881f8e8206effe30847ab',
    messagingSenderId: '277847481010',
    projectId: 'smart-task-manager-2026',
    authDomain: 'smart-task-manager-2026.firebaseapp.com',
    storageBucket: 'smart-task-manager-2026.firebasestorage.app',
  );
}
